Projector - add projetor repo & command to play/replay projector
makinacorpus/php-goat pull request #3
Opened 2020-05-05 09:51 UTC by SimonMellerin

2020-05-05 09:57 UTC, SimonMellerin commented on src/Bridge/Symfony/Resources/config/projector.yaml
> +        tags: ["console.command"]
add a line

2020-05-05 09:57 UTC, SimonMellerin commented on src/Domain/Command/ProjectorPlayCommand.php
> +    protected static $defaultName = 'projector:play';
what if each goat command started by 'goat:...'

2020-05-05 09:57 UTC, SimonMellerin commented on src/Domain/Command/ProjectorPlayCommand.php
> +        $output->writeln(\sprintf("%d events has to be processed", $total));
has(ve) may be

2020-05-05 09:57 UTC, SimonMellerin commented on src/Domain/Command/ProjectorPlayCommand.php
> +        $output->writeln(\sprintf("%d events(s) has(ve) been correctly process, %d failed.", $total - $failed, $failed));
mutli line ?

2020-05-05 09:57 UTC, SimonMellerin commented on src/Domain/Projector/ProjectorRepository.php
> +        foreach ($this->projectors as $projector) {
it's possible there's no projector at all !

2020-05-05 10:13 UTC, pounard requested changes
Overall this seems very good, some details need to be fixed.

2020-05-05 10:13 UTC, pounard commented on src/Bridge/Symfony/Resources/config/projector.yaml
> +            public: false
Careful with indentation, you indent twice here.

2020-05-05 10:13 UTC, pounard commented on src/Domain/Command/ProjectorPlayCommand.php
> +            ->addOption('date', null, InputOption::VALUE_REQUIRED, 'Play projector from a specific date (format Y-m-d)')
`--reset` and `--date` should probably mutually exclusive, otherwise one could reset a projection and populate it partially ?

2020-05-05 10:13 UTC, pounard commented on src/Domain/Command/ProjectorPlayCommand.php
> +            ->addArgument('identifier', InputArgument::REQUIRED, 'Projector identifier or className')
Instead of `identifier` as argument name, why not simply `projector`, would it be more meaningful ?

2020-05-05 10:13 UTC, pounard commented on src/Domain/Command/ProjectorPlayCommand.php
> +        if (!$projector = $this->projectorRepository->findByIdentifierOrClassName($identifier)) {
Why not raising an exception directly in `::findByIdentifierOrClassName()` in case of projector not found ?

2020-05-05 10:13 UTC, pounard commented on src/Domain/Command/ProjectorPlayCommand.php
> +        if($input->getOption('reset')) {
Missing space after `if`.

2020-05-05 10:13 UTC, pounard commented on src/Domain/Command/ProjectorPlayCommand.php
> +        if($date) {
Missing space after `if`, I should setup a CS fixer.

2020-05-05 10:13 UTC, pounard commented on src/Domain/Command/ProjectorPlayCommand.php
> +                $failed++;
Error should probably not be completely silent, may be it worth the shot to output the error message here, even if the process continues, so that the console output will yield errors. Also, outputing full exception trace when output is very verbose could be a plus.

2020-05-05 10:13 UTC, pounard commented on src/Domain/DependencyInjection/Compiler/DomainConfigurationPass.php
>                  $dispatcherDef->addMethodCall('setProjectors', [$references]);
Where is the `$references` variable populated ? Are keys being names ?

2020-05-05 10:13 UTC, pounard commented on src/Domain/DependencyInjection/Compiler/DomainConfigurationPass.php
>                  $dispatcherDef->addMethodCall('setProjectors', [$references]);
Oh, that's a typo, the right variable is `$projectorsRef` right ?

2020-05-05 10:13 UTC, pounard commented on src/Domain/DependencyInjection/Compiler/DomainConfigurationPass.php
>                  $dispatcherDef->addMethodCall('setProjectors', [$references]);
Another suggestion, now that we have a registry, you should add a `getAll(): iterable` method on it, and inject the registry into the dispatcher instead of the arbitrary projector references list.

2020-05-05 10:13 UTC, pounard commented on src/Domain/Projector/Projector.php
> +    public $identifier;
I don't really like properties on interfaces, may be a `getIdentifier(): string` method instead ?

2020-05-05 10:13 UTC, pounard commented on src/Domain/Projector/ProjectorRepository.php
> +class ProjectorRepository
`ProjectorRegistry` may be a better name here.

2020-05-05 10:13 UTC, pounard commented on src/Domain/Projector/ReplayableProjector.php
> +    public function reset(): void;
Please document the method, `reset()` -> delete everything and prepare to replay.

2020-05-05 10:13 UTC, pounard commented on src/Domain/Projector/ProjectorRepository.php
> +        $this->projectors = $projectors;
In order to avoid double initialisation and make the class pseudo-immutable, I would write:

```php
    public function setProjectors(iterable $projectors): void
    {
        if (null !== $this->projectors) {
            throw new \BadMethodCallException("Projector registry cannot be initialized twice.");
        }

        $this->projectors = $projectors;
    }
```

2020-05-05 10:13 UTC, pounard commented on src/Domain/Projector/ProjectorRepository.php
> +        foreach ($this->projectors as $projector) {
I would add a method such as `private function isInitializedOrDie()` that would raise a `\BadMethodCallException` if `null === $this->projectors` to avoid partially initialised registry usages.

2020-05-05 10:13 UTC, pounard commented on src/Domain/Projector/ProjectorRepository.php
> +        foreach ($this->projectors as $projector) {
This method would need to be called in `findByIdentifier()` as well as in `findByClassName()` and all other accessors.

2020-05-05 10:14 UTC, pounard commented on src/Domain/Command/ProjectorPlayCommand.php
> +                $failed++;
Next step, for later, will be to add instrumentation here, but let's keep this PR simple.

2020-05-05 10:20 UTC, pounard commented on src/Domain/Command/ProjectorPlayCommand.php
> +    protected static $defaultName = 'projector:play';
Why not, indeed.

2020-05-05 14:31 UTC, SimonMellerin commented on src/Domain/Command/ProjectorPlayCommand.php
> +    protected static $defaultName = 'projector:play';
I'm gonna do this in another PR

2020-05-05 14:36 UTC, pounard commented on src/Domain/Command/ProjectorPlayCommand.php
> +    protected static $defaultName = 'projector:play';
Yes, and this may be a BC break, so you will need to set command aliases using the old names.

2020-05-05 14:53 UTC, SimonMellerin commented on src/Domain/DependencyInjection/Compiler/DomainConfigurationPass.php
>                  $dispatcherDef->addMethodCall('setProjectors', [$references]);
should I removed $projectors from Dispatcher or should I cache it ?

2020-05-05 15:00 UTC, pounard commented on src/Domain/DependencyInjection/Compiler/DomainConfigurationPass.php
>                  $dispatcherDef->addMethodCall('setProjectors', [$references]);
Remove it, inject the registry instead and call getAll() each time you need it, that's fine, since the array will never modified it won't be visible at all in term of permances.

2020-05-06 07:56 UTC, merged

2020-05-06 08:00 UTC, pounard commented on src/Bridge/Symfony/Resources/config/projector.yaml
> +    Goat\Domain\Command\ProjectorPlayCommand:
Juste un détail, ce service devrait être dans un fichier `event-projector.yaml` et n'être chargé que si `$consoleEnabled` .